name: EffectClear
main: NikosProGamer\EffectClear\EffectClear
version: 1.0.0
api: 3.0.0, 4.0.0
author: NikosProGamer
description: A plugin by NikosProGamer that removes all bad effects from you!

commands:
  bless:
    description: Bless yourself by removing bad effects!
permissions:
  bless:
    default: op
    description: Allows player to bless himself!
    children:
